version: '3'
services:
    nginx:
        build:
            dockerfile: ./docker/nginx.dockerfile
            context: .
        image: vpsdecodes/nginx
        container_name: nginx-vps-decodes
        volumes: 
          - /home:/etc/nginx/html
        ports:
            - "80:80"
            - "443:443"
        networks: 
            - production-network
        depends_on:
            - leilaofake1
#            - leilaofake2

    leilaofake1:
        build:
            dockerfile: ./docker/leilaofake.dockerfile
            context: .
        image: antonycharles/leilaofake
        container_name: leilao-fake-1
        volumes: 
            - /home/apps/leilaofake/logs/:/app/logs/
            - /home/apps/leilaofake/imagens:/app/wwwroot/imagens
        ports:
            - "80"
            - "443"
        networks: 
            - production-network
            - postgres-network

#    leilaofake2:
#        build:
#            dockerfile: ./docker/leilaofake.dockerfile
#            context: .
#        image: antonycharles/leilaofake
#        container_name: leilao-fake-2
#        volumes: 
#            - /home/apps/leilaofake/logs/:/app/logs/
#            - /home/apps/leilaofake/imagens:/app/wwwroot/imagens
#        ports:
#            - "80"
#            - "443"
#        networks: 
#            - production-network
#            - postgres-network

networks:
    production-network:
        external: true
    postgres-network:
        external: true